### ISSUE TITLE
this.$fiery(collectionReference, options) promise

### ISSUE THREAD

**Issue by nmf2** [fiery-data/fiery-vue#10]
Hello, is it possible to await the creation of the object resulting from the call above?

What I'm trying to do exactly is this:

```
methods: {
    async test () {
      var test = await this.$fiery(fs.collection('collectionName'))
      if(test[0].prop) ....
    }
}
```
Is there any way to achieve this?

PS: You did a great job with this lib, man, seriously. A life saver!

**Comment by ClickerMonkey** [comment]
It would be something more like this:
```
var test = this.$fiery(fs.collection('collectionName'));
await this.$fiery.entryFor(test).promise;
```
`test` is just an array in this example - so calling await on that won't work. But you can get the promise! There are some caveats with this though:

If you have a local copy of that collection (because firestore keeps a local cache of everything it can) the promise should resolve basically immediately with that local copy. You could still have new remote data that has not been brought in at this point - so don't expect `test` to be in sync with the remote source.

If you don't have a local copy of that collection I don't recall whether it will return immediately with an empty array OR whether it will wait until data is fetched from the remote source. This is something tied to how firestore behaves, and not this library.

There is an onSuccess option you can pass like so, this is invoked initially and each time the collection is updated:

```
this.$fiery(fs.collection('collectionName'), {
  onSuccess: (collectionData) => {
    // when data is initially loaded and every time it's updated
  }
});
```

**Comment by nmf2** [comment]
Perfect! Thank you, man!

**Comment by ClickerMonkey** [comment]
No problem!
